### PR TITLE
use pkgs.stdenv.cc.bintools.dynamicLinker for ld.so path

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Why is mergify merging main into the PR? That creates extremely convoluted histories and is making it really hard to understand afterwards what happened.

**Comment by Mic92** [comment]
> Why is mergify merging main into the PR? That creates extremely convoluted histories and is making it really hard to understand afterwards what happened.

This is what they say:

https://docs.mergify.com/actions/queue/#update-method-rebase

**Comment by Mic92** [comment]
So far the PR merge commits look ok to me: https://github.com/Mic92/nix-ld/commit/346c0c862a4c1d75896656636d71632b9ca37864

**Comment by SuperSandro2000** [comment]
``git log --oneline --graph`` is already starting to get a bit confusing. Before the history was really straight forward but for this PR the fork of point is some other branch and things start to layer across each other instead of having simple parallel lines.

```
*   5e696c9 (HEAD -> main, tag: 1.2.1, origin/main, origin/HEAD) Merge pull request #57 from Mic92/aarch64-build
|\
| * a812f82 fix aarch64 build
| * 3a938b4 enable aarch64
|/
*   346c0c8 Merge pull request #56 from Mic92/joerg-ci
|\
| *   6beaaa3 Merge branch 'main' into joerg-ci
| |\
| |/
|/|
* |   8b964f9 (tag: 1.2.0) Merge pull request #52 from Mic92/exe-support
|\ \
| | * b40fa74 (origin/joerg-ci) use pkgs.stdenv.cc.bintools.dynamicLinker for ld.so path
| |/
| * e70b775 drop flake-utils
| * ca4a665 avoid integer underflow when calling memset with 0
|/
*   a7a0a67 Merge pull request #54 from Mic92/nix-ld
|\
| * 13ce3d5 (origin/nix-ld) replace bors with mergify
* | 03a2638 (origin/staging) Merge #53
|\|
| * cf8eb9e add fallback mechanism if environment variables are unset
| * 238731e flake.lock: Update
|/
*   29f15b1 Merge pull request #51 from debrutal/patch-1
|\
| * 994aacc Update README.md
|/
*   1a9d253 (tag: 1.1.0) Merge #49
|\
| * 58885b3 Update README.md
| * f5a0262 readme: availability typo
|/
*   c60c833 Merge #47
|\
| * c7149c0 allow nix-ld to be run as an executable
|/
*   1785245 Merge #44
|\
| * f5983af README: fix example for python wrapper
|/
*   c56e2e6 Merge #43
|\
| * 23b7eeb README: document how to deal with interpreter
|/
*   27b651c Merge #41
|\
| * e1a3681 add bors.toml
| * 07b5a71 print errors to stderr
* |   45097e5 Merge pull request #39 from jcharum/patch-1
|\ \
| * | c3d43d3 Correct URL of blog post
|/ /
* | 2e26ccf Merge pull request #37 from Mic92/blog
|\|
| * c6bb6d6 README: link to blog post
|/
*   2df31a7 Merge pull request #36 from Mic92/ci
```

**Comment by Mic92** [comment]
I will give the rebase method a try eventually

**Pull request merged**
